chore: Bump hedgedoc to 1.9.9
adfinis/helm-charts pull request #1089
Opened 2023-08-10 21:48 UTC by gianklug

# Description

Updated the Hedgedoc Chart to **1.9.9**.

This mainly includes a security fix for [CVE-2023-38487](https://github.com/hedgedoc/hedgedoc/security/advisories/GHSA-7494-7hcf-vxpg).

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated the changelog with an `artifacthub.io/changes` annotation in `Chart.yaml`, check the [example](docs/development.md#Changelog) in the documentation.
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [ ] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

2023-08-10 22:02 UTC, tongpu requested changes

2023-08-10 22:02 UTC, tongpu commented on charts/hedgedoc/Chart.yaml
> +      description: "Update to HedgeDoc 1.9.9, see [GitHub](https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.9) for the release notes."
Adding a link to the security advisory is probably a good idea for a security bugfix release:

```suggestion
      description: "Update to HedgeDoc 1.9.9, see [GitHub](https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.9) for the release notes."
      links:
        - name: CVE-2023-38487 / GHSA-7494-7hcf-vxpg
          url: https://github.com/hedgedoc/hedgedoc/security/advisories/GHSA-7494-7hcf-vxpg
```

2023-08-11 06:13 UTC, eyenx approved these changes

2023-08-11 06:52 UTC, tongpu commented on charts/hedgedoc/Chart.yaml
> +          url: https://github.com/hedgedoc/hedgedoc/security/advisories/GHSA-7494-7hcf-vxpg
Seems like the lines have been added multiple times.
```suggestion
```

2023-08-14 08:10 UTC, tongpu approved these changes

2023-08-14 08:18 UTC, merged