fix: VaultAutopilotHealthy alert name
adfinis/helm-charts pull request #1157
Opened 2023-12-04 15:49 UTC by in0rdr

I would like to improve the alert name for the autopilot.

* https://developer.hashicorp.com/vault/docs/internals/telemetry/metrics/all#vault-autopilot-healthy
* https://developer.hashicorp.com/vault/docs/internals/telemetry/metrics/all#vault-autopilot-node-healthy

Also, I noticed a link that no longer points to a meaningful location. We can remove it.

2023-12-04 16:14 UTC, pree approved these changes
Thanks, please also update `security-apps` to include the new version.

2023-12-04 16:18 UTC, pree commented
@adfinis/helm-charts what do you think about bumping this chart to `1.0.0` ?

2023-12-04 16:39 UTC, eyenx commented
> @adfinis/helm-charts what do you think about bumping this chart to `1.0.0` ?

Hmm read fix and this big bump and was like why? Are you sure this stuff is 1.0 ready?

2023-12-05 09:27 UTC, in0rdr commented
Looking at https://semver.org/#spec-item-5, we only need to care about the "breaking" change if we have `1.*`? Because probably nobody takes your word for it before `1.*` anyways (i.e., it's not yet a public API so you can do whatever). Let me revert to `0.3.0`, I was not aware of that rule nr. 5

2023-12-05 10:41 UTC, pree requested changes

2023-12-05 10:41 UTC, pree commented on charts/vault-monitoring/values.yaml
> +        description: There has been an increased number of failed Vault responses in the last 20 minutes
How has this changed? It's still `for: 15m`

2023-12-05 12:25 UTC, tongpu commented
> Looking at https://semver.org/#spec-item-5, we only need to care about the "breaking" change if we have `1.*`? Because probably nobody takes your word for it before `1.*` anyways (i.e., it's not yet a public API so you can do whatever). Let me revert to `0.3.0`, I was not aware of that rule nr. 5

I honestly believe that we depend on too many downstream charts in our `*-apps` charts that it's going to be close to impossible to ever provide a stable public API.

2023-12-05 15:08 UTC, hairmare commented
> I honestly believe that we depend on too many downstream charts in our `*-apps` charts that it's going to be close to impossible to ever provide a stable public API.

i believe that as well, but this is vault-monitoring hence the reasoning doesn't apply

2024-06-14 14:39 UTC, closed without merging